# Generated by Django 4.1 on 2022-08-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='varition_category',
            new_name='variation_category',
        ),
    ]
